import { useMemo, useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Image } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { IconLocationOutline, IconHeartOutline, IconPencilOutline, IconChevronBack, IconLogOutOutline, IconChatBubbleOutline, IconDocumentOutline, IconBellOutline, IconHelpCircleOutline } from '../../components/Icons';
import { useAuth } from '../../contexts/AuthContext';
import { useTheme } from '../../contexts/ThemeContext';
import { ConfirmationDialog } from '../../components/confirmation-dialog';

type Row={label:string;hint:string;route:string;icon:React.ComponentType<{size?:number;color?:string}>};
export default function AccountScreen(){const t=useTheme(),s=useMemo(()=>styles(t),[t]);const{user,logout}=useAuth();const[confirming,setConfirming]=useState(false);const name=String(user?.fullName||user?.email||'حسابي'),email=String(user?.email||''),avatar=typeof user?.avatarUrl==='string'?user.avatarUrl:null;const groups:Row[][]=[[{label:'العناوين',hint:'إدارة عناوين التوصيل',route:'/addresses',icon:IconLocationOutline},{label:'المفضلة',hint:'مطاعم ومنتجات محفوظة',route:'/favorites',icon:IconHeartOutline},{label:'تعديل الحساب',hint:'الاسم والهاتف والبريد',route:'/profile/edit',icon:IconPencilOutline}],[{label:'الإشعارات',hint:'تحديثات طلباتك',route:'/notifications',icon:IconBellOutline},{label:'الأسئلة الشائعة',hint:'إجابات سريعة',route:'/faq',icon:IconHelpCircleOutline},{label:'الدعم',hint:'تواصل معنا',route:'/support',icon:IconChatBubbleOutline},{label:'الشروط والخصوصية',hint:'معلومات قانونية',route:'/legal',icon:IconDocumentOutline}]];const exit=async()=>{await logout();router.replace('/(auth)')};return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text style={s.title}>حسابي</Text><TouchableOpacity style={s.identity} onPress={()=>router.push('/profile/edit')}><View style={s.avatar}>{avatar?<Image source={{uri:avatar}} style={s.avatarImage}/>:<Text style={s.initial}>{name.charAt(0)}</Text>}</View><View style={s.identityText}><Text style={s.name} numberOfLines={1}>{name}</Text>{email?<Text style={s.email} numberOfLines={1}>{email}</Text>:null}</View><IconChevronBack size={19} color={t.colors.textMuted}/></TouchableOpacity>{groups.map((group,index)=><View key={index} style={s.group}>{group.map((row,i)=>{const Icon=row.icon;return <TouchableOpacity key={row.route} style={[s.row,i>0&&s.divider]} onPress={()=>router.push(row.route as never)}><View style={s.icon}><Icon size={20} color={t.colors.primary}/></View><View style={s.rowText}><Text style={s.label}>{row.label}</Text><Text style={s.hint}>{row.hint}</Text></View><IconChevronBack size={18} color={t.colors.textMuted}/></TouchableOpacity>})}</View>)}<TouchableOpacity style={s.logout} onPress={()=>setConfirming(true)}><IconLogOutOutline size={20} color={t.colors.error}/><Text style={s.logoutText}>تسجيل الخروج</Text></TouchableOpacity></ScrollView><ConfirmationDialog visible={confirming} title="تسجيل الخروج" message="هل تريد إنهاء جلستك الحالية؟" confirmLabel="خروج" destructive onCancel={()=>setConfirming(false)} onConfirm={exit}/></SafeAreaView>}
const styles=(t:ReturnType<typeof useTheme>)=>StyleSheet.create({safe:{flex:1,backgroundColor:t.colors.background},content:{padding:20,paddingBottom:110},title:{...t.typography.titleLarge,fontFamily:t.fonts.bold,color:t.colors.text,marginBottom:18},identity:{flexDirection:'row',alignItems:'center',gap:12,paddingBottom:22,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:t.colors.borderLight},avatar:{width:52,height:52,borderRadius:16,backgroundColor:t.colors.primary,alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImage:{width:'100%',height:'100%'},initial:{fontSize:22,fontFamily:t.fonts.bold,color:t.colors.white},identityText:{flex:1},name:{...t.typography.body,fontFamily:t.fonts.bold,color:t.colors.text},email:{...t.typography.caption,color:t.colors.textSecondary,marginTop:2},group:{marginTop:22,borderTopWidth:StyleSheet.hairlineWidth,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:t.colors.borderLight},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14},divider:{borderTopWidth:StyleSheet.hairlineWidth,borderColor:t.colors.borderLight},icon:{width:38,height:38,borderRadius:12,backgroundColor:t.colors.primarySoft,alignItems:'center',justifyContent:'center'},rowText:{flex:1},label:{...t.typography.body,fontFamily:t.fonts.medium,color:t.colors.text},hint:{...t.typography.caption,color:t.colors.textMuted,marginTop:1},logout:{marginTop:30,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingVertical:14},logoutText:{...t.typography.body,fontFamily:t.fonts.bold,color:t.colors.error}});
