import { useCallback, useEffect, useMemo, useState } from 'react';
import { View, Text, FlatList, TouchableOpacity, StyleSheet, ActivityIndicator, Image } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getOrders } from '../../api/client';
import { formatPrice } from '../../constants/theme';
import { useTheme } from '../../contexts/ThemeContext';
import { IconPackageOutline, IconStoreOutline, IconTruckOutline } from '../../components/Icons';
import { EmptyState } from '../../components/ui';
import { activeOrderStatuses, getOrderStatus } from '../../lib/order-status';
import { addNotificationListener } from '../../hooks/useNotifications';

type Order={id:string;orderNumber?:string;status?:string;total?:number;createdAt?:string;driverId?:string|null;merchantProfile?:{storeName?:string;logoUrl?:string|null};items?:Array<{quantity?:number}>};
const dateLabel=(value?:string)=>{if(!value)return '';const d=new Date(value),diff=Math.floor((Date.now()-d.getTime())/86400000);return diff===0?'اليوم':diff===1?'أمس':d.toLocaleDateString('ar-DZ',{day:'numeric',month:'short'});};

export default function OrdersScreen(){
 const t=useTheme(),s=useMemo(()=>styles(t),[t]);const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true);
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const result=await getOrders();setOrders(Array.isArray(result)?result as Order[]:[])}catch{setOrders([])}finally{if(!silent)setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);useFocusEffect(useCallback(()=>{load(true)},[load]));
 useEffect(()=>{const id=setInterval(()=>load(true),10000);return()=>clearInterval(id)},[load]);
 useEffect(()=>{const unsubscribe=addNotificationListener((p)=>{if(p.type?.includes('order'))load(true)});return()=>{unsubscribe()}},[load]);
 const active=orders.filter(o=>activeOrderStatuses.has(o.status||'')),past=orders.filter(o=>!activeOrderStatuses.has(o.status||''));
 const render=({item}:{item:Order})=>{const meta=getOrderStatus(item.status);const canTrack=Boolean(item.driverId&&['picked_up','on_the_way'].includes(item.status||''));const qty=item.items?.reduce((n,x)=>n+(x.quantity||1),0)||0;return <TouchableOpacity style={s.order} onPress={()=>router.push(`/order/${item.id}`)} activeOpacity={.84}><View style={s.logo}>{item.merchantProfile?.logoUrl?<Image source={{uri:item.merchantProfile.logoUrl}} style={s.image}/>:<IconStoreOutline size={21} color={t.colors.primary}/>}</View><View style={s.main}><View style={s.top}><Text style={s.store} numberOfLines={1}>{item.merchantProfile?.storeName||'متجر'}</Text><Text style={[s.pill,{color:meta.tone==='success'?t.colors.success:meta.tone==='error'?t.colors.error:t.colors.primary,backgroundColor:(meta.tone==='success'?t.colors.success:meta.tone==='error'?t.colors.error:t.colors.primary)+'12'}]}>{meta.label}</Text></View><Text style={s.meta}>#{item.orderNumber||item.id.slice(-6)} · {dateLabel(item.createdAt)}{qty?` · ${qty} منتجات`:''}</Text><View style={s.bottom}><Text style={s.price}>{formatPrice(item.total)}</Text>{canTrack?<TouchableOpacity onPress={(e)=>{e.stopPropagation();router.push({pathname:'/order/[id]/tracking',params:{id:item.id}})}} style={s.track}><IconTruckOutline size={15} color={t.colors.primary}/><Text style={s.trackText}>تتبع</Text></TouchableOpacity>:<Text style={s.detail}>عرض التفاصيل</Text>}</View></View></TouchableOpacity>};
 // Keeping sections as data avoids two independently scrolling lists.
 const data=[...active.map(x=>({...x,_section:'طلبات جارية'})),...past.map(x=>({...x,_section:'طلبات سابقة'}))] as (Order&{_section:string})[];
 return <SafeAreaView style={s.safe} edges={['top']}><View style={s.header}><Text style={s.title}>طلباتي</Text><Text style={s.sub}>تابع طلباتك الحالية والسابقة</Text></View>{loading?<ActivityIndicator style={s.loader} color={t.colors.primary}/>:<FlatList data={data} keyExtractor={x=>x.id} contentContainerStyle={s.list} ListEmptyComponent={<EmptyState kind="orders" title="لا طلبات بعد" message="عند تقديم أول طلب سيظهر هنا" actionLabel="تصفح المطاعم" onAction={()=>router.push('/(tabs)')}/>} renderItem={({item,index})=><>{(index===0||data[index-1]._section!==item._section)&&<Text style={s.section}>{item._section}</Text>}{render({item})}</>}/>}</SafeAreaView>;
}
const styles=(t:ReturnType<typeof useTheme>)=>StyleSheet.create({safe:{flex:1,backgroundColor:t.colors.background},header:{paddingHorizontal:20,paddingTop:18,paddingBottom:12},title:{...t.typography.titleLarge,fontFamily:t.fonts.bold,color:t.colors.text},sub:{...t.typography.caption,color:t.colors.textSecondary,marginTop:2},loader:{flex:1},list:{padding:20,paddingTop:4,paddingBottom:110},section:{...t.typography.caption,fontFamily:t.fonts.bold,color:t.colors.textSecondary,marginTop:16,marginBottom:8},order:{flexDirection:'row',gap:12,paddingVertical:14,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:t.colors.borderLight},logo:{width:52,height:52,borderRadius:14,backgroundColor:t.colors.surface,alignItems:'center',justifyContent:'center',overflow:'hidden'},image:{width:'100%',height:'100%'},main:{flex:1},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},store:{flex:1,...t.typography.body,fontFamily:t.fonts.bold,color:t.colors.text},pill:{...t.typography.caption,fontFamily:t.fonts.medium,paddingHorizontal:8,paddingVertical:3,borderRadius:8},meta:{...t.typography.caption,color:t.colors.textMuted,marginTop:3},bottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8},price:{...t.typography.body,fontFamily:t.fonts.bold,color:t.colors.text},detail:{...t.typography.caption,color:t.colors.textSecondary},track:{flexDirection:'row',gap:4,alignItems:'center'},trackText:{...t.typography.caption,fontFamily:t.fonts.bold,color:t.colors.primary}});
