-- AlterTable
ALTER TABLE "merchant_profiles"
ADD COLUMN "has_offers" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "rating_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "rating_count" INTEGER NOT NULL DEFAULT 0;
